pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/sundar-mungara/devops-project.git'
            }
        }
        stage('Build & Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: '799561935', usernameVariable: 'sundarmungar', passwordVariable: 'Gnan@2601mung')]) {
                    sh 'docker build -t sundarmungar/frontend:latest frontend/'
                    sh 'docker build -t sundarmungar/backend:latest backend/'
                    sh 'echo "$DOCKER_PASSWORD" | docker login -u "sundarmungar" --password-stdin'
                    sh 'docker push sundarmungar/frontend:latest'
                    sh 'docker push sundarmungar/backend:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}
